### ISSUE TITLE
[FEATURE] AzureML SDK v2 support

### ISSUE THREAD

**Issue by shohei1029** [recommenders-team/recommenders#1833] opened 2022-10-25 02:20 UTC
### Description

AzureML SDK v2 was GA at Ignite 2022. 
We saw the codes in [the examples](https://github.com/microsoft/recommenders/tree/main/examples) are based on SDK v1. 
Do we have any plans to update the examples to follow SDK v2?

**Comment by miguelgfierro** [comment] 2022-10-27 15:44
hi @shohei1029, at the moment, our team doesn't have bandwidth to do this task. Is this something that you could support?

**Comment by miguelgfierro** [comment] 2024-05-06 14:49
duplicate of #2066

**Closed by miguelgfierro** 2024-05-06 14:49 UTC
Labels: enhancement
