### ISSUE TITLE
[ASK] No module named 'recommenders'

### ISSUE THREAD

**Issue by shasha920** [recommenders-team/recommenders#1968] opened 2023-08-16 04:40 UTC
### Description
Hi, I try to from recommenders.models.tfidf.tfidf_utils import TfidfRecommender, then get error: No module named 'recommenders', So I use :!pip install git+https://github.com/microsoft/recommenders.git,  in google colab get error again : ERROR: Package 'recommenders' requires a different Python: 3.10.12 not in '<3.10,>=3.6',  so I change environment in anaconda, get another error: ERROR: Could not build wheels for safetensors, which is required to install pyproject.toml-based projects. Seems can't !pip in google colab and anaconda, is anyone has same problem like me?

**Comment by miguelgfierro** [comment] 2023-08-17 18:15
Duplicate of https://github.com/recommenders-team/recommenders/issues/1928

We are working to support python 3.10

**Closed by miguelgfierro** 2023-08-17 18:15 UTC
Labels: help wanted, duplicate

**Comment by shasha920** [comment] 2023-08-17 18:51
> Duplicate of #1928
> 
> We are working to support python 3.10

Thanks! How long can be expected? Looking forward to it!
